In [1]:
print("Ahoj světe!")

Ahoj světe!


# Moje první analýza

Tento notebook procvičuje práci s Jupyter Notebooky, numpy a matplotlib.

## Vzorec

Pythagorova věta:

$$ c = \sqrt{a^2 + b^2} $$

Inline použití: pro $a = 3$ a $b = 4$ vyjde $c = 5$.

## Obrázek

![Logo Pythonu](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)


# automatický výstup poslední hodnoty v buňce
a = 3
b = 4
c = (a**2 + b**2) ** 0.5
c

# instalace knihovny rovnou z notebooku
!uv add cowsay

In [2]:
# instalace knihovny rovnou z notebooku
!uv add cowsay


Resolved 112 packages in 6ms
Audited 108 packages in 650ms


In [3]:
# použití nainstalované knihovny
import cowsay
cowsay.cow("Ahoj z Jupyteru!")

  ________________
| Ahoj z Jupyteru! |
                \
                 \
                   ^__^
                   (oo)\_______
                   (__)\       )\/\
                       ||----w |
                       ||     ||


print("  _

In [4]:
print(" _"
      "/ \ "
      "    "
          )

 _/ \     


In [5]:
import numpy as np
import time

n = 10_000_000
py_list  = list(range(n))
np_array = np.arange(n)

# Varianta 1 – klasická for smyčka
result_loop = [0] * n
start = time.time()
for i in range(n):
    result_loop[i] = py_list[i] * 2
t_loop = time.time() - start

# Varianta 2 – list comprehension
start = time.time()
result_lc = [x * 2 for x in py_list]
t_lc = time.time() - start

# Varianta 3 – NumPy vektorizace
start = time.time()
result_np = np_array * 2
t_np = time.time() - start

print(f"for smyčka:         {t_loop:.3f} s")
print(f"list comprehension: {t_lc:.3f} s")
print(f"NumPy:              {t_np:.3f} s")
print(f"\nNumPy vs for smyčka:        {t_loop / t_np:.0f}×")
print(f"NumPy vs list comprehension: {t_lc / t_np:.0f}×")


for smyčka:         1.319 s
list comprehension: 1.117 s
NumPy:              0.429 s

NumPy vs for smyčka:        3×
NumPy vs list comprehension: 3×


In [6]:
import numpy as np

# Ze seznamu
a = np.array([1, 2, 3, 4, 5])
a


array([1, 2, 3, 4, 5])

In [7]:
# Číselná řada – arange(start, stop, krok)
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [8]:
# Rovnoměrně rozložené hodnoty – ideální pro časové osy
np.linspace(0, 1, 6)   # 6 hodnot od 0 do 1 včetně


array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [9]:
np.zeros(4)


array([0., 0., 0., 0.])

In [10]:
np.ones((2, 3))



array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Gaussův šum – realistické biomedicínské hodnoty
noise = np.random.normal(loc=0, scale=0.1, size=8)
np.round(noise, 3)


array([ 0.107,  0.042,  0.122,  0.147, -0.166,  0.021,  0.013, -0.019])